### ISSUE TITLE
option for parallel processing

### ISSUE THREAD

**Issue by Akanksha2511** [WGLab/LIQA#12]
Hi, 

Was wondering if there is an option for using multiple threads. As my data is huge and the quantification does not finish on the maximum allotted time on our HPC. 

Thanks, 
Akanksha

**Comment by Jungal10** [comment]
Any news in this regard? I suffer with the same issue. Each bam file is 72h

**Comment by agouru55** [comment]
Hi! Yes there is an option for multiprocessing at the quantify step. You can update LIQA to latest version and find more info at: https://github.com/WGLab/LIQA/pull/28

**Comment by yvazirabad** [comment]
Hello,

Why was this code never added to the main commit trail? It seems to be very helpful?
