### ISSUE TITLE
Output file  explanation

### ISSUE THREAD

**Issue by gmoneyomics** [WGLab/LIQA#13]
Hi, 

Could you please explain the "geneDASResults" file? The readme says the following:
```
	"geneDASResults" file: Gene-based test results file with 3 columns:
		• Column 1: gene name
		• Column 2: test P-Value
		• Column 3: Hellinger distance which measures the splicing difference between two conditions for a gene in terms of isoform relative abundances
```
However the file I am getting only has two columns
```
RNLS    0.327411022732461
LOC115598243    0.0449462797534785
CHD9    0.00752205014986429
```
Is the second column the p-value?

Thank  you, 

Ariel

**Comment by agouru55** [comment]
Yes, this represents the P-Value. The Usage page has more clarification on this value.
