### ISSUE TITLE
"liqa -task refgene" but there are no result

### ISSUE THREAD

**Issue by JD12138** [WGLab/LIQA#14]
hello, 
    I use "liqa -task refgene -ref tmp.gtf -format gtf -out new2_AR_compare.annotated.gtf.refgene",there is no error ,with an out "10000 genes are being processed...",but the result file is 0.
 Do you know the reason?

**Comment by rkyger-git** [comment]
Hello WGLab, 
I ran into the same issue above as well. 
Do you have any solutions to this issue?

**Comment by Shafimahmud1** [comment]
I got the same error

**Comment by huyustats** [comment]
> I got the same error

Hi,

Thanks for using LIQA. Usually this step only output genes with 2 or more isoforms. May I have the GTF file you used for example? I am happy to dig it out the reason. Thanks!

**Comment by Shafimahmud1** [comment]
Hi, this is my gtf files  which I have retrieved from refseq for Yeast

#gtf-version 2.2
#!genome-build R64
#!genome-build-accession NCBI_Assembly:GCF_000146045.2
#!annotation-source SGD R64-4-1
NC_001133.9	RefSeq	gene	1807	2169	.	-	.	gene_id "YAL068C"; transcript_id ""; db_xref "GeneID:851229"; gbkey "Gene"; gene "PAU8"; gene_biotype "protein_coding"; locus_tag "YAL068C"; partial "true"; 
NC_001133.9	RefSeq	transcript	1807	2169	.	-	.	gene_id "YAL068C"; transcript_id "NM_001180043.1"; db_xref "GeneID:851229"; gbkey "mRNA"; gene "PAU8"; locus_tag "YAL068C"; partial "true"; product "seripauperin PAU8"; transcript_biotype "mRNA"; 
NC_001133.9	RefSeq	exon	1807	2169	.	-	.	gene_id "YAL068C"; transcript_id "NM_001180043.1"; db_xref "GeneID:851229"; gene "PAU8"; locus_tag "YAL068C"; partial "true"; product "seripauperin PAU8"; transcript_biotype "mRNA"; exon_number "1";

**Comment by JeanGuy777** [comment]
Hi WGLab,

I have the same problem as well. Prior to run liqa -task refgene, I converted my gff file in gft using gffread:
$> gffread -E ../Leishmania_Scripts/reference/TriTrypDB-62_LinfantumJPCM5.gff -T -o  TriTrypDB-62_LinfantumJPCM5.gtf

See below the first four lines:
LinJ.11 VEuPathDB       transcript      2624    3136    .       +       .       transcript_id "LINF_110005000-T1"; gene_id "LINF_110005000"
LinJ.11 VEuPathDB       exon    2624    3136    .       +       .       transcript_id "LINF_110005000-T1"; gene_id "LINF_110005000";
LinJ.11 VEuPathDB       CDS     2624    3136    .       +       0       transcript_id "LINF_110005000-T1"; gene_id "LINF_110005000";
LinJ.11 VEuPathDB       transcript      3576    4682    .       +       .       transcript_id "LINF_110005100-T1"; gene_id "LINF_110005100"

Afterwards, liqa gave no error code:
$> liqa -task refgene -ref TriTrypDB-62_LinfantumJPCM5.gtf -format gtf -out example.refgene.test
8748 genes are being processed...

$> ls -al
-rwxrwxrwx 1 jeang jeang       **0** Nov 29  2023 example.refgene.test

Thank you,
Sincerely,
