### ISSUE TITLE
Execution halted: detecting differential isoform  

### ISSUE THREAD

**Issue by allapadma** [WGLab/LIQA#17]
Hi, 

I have been facing this error: 

Error in read.table(input.file[1]) : no lines available in input
Execution halted

Can you please help get around this ? 

Thank you.

**Comment by benpiticaru** [comment]
I am also having the same issue:

Error in read.table(input.file[1]) : no lines available in input
Execution halted

**Comment by benpiticaru** [comment]
I had the same issue but it was fixed once I put the file into a list as shown in the usage section Step 3: Detecting differential splicing gene/isoform between condition.

**Comment by allapadma** [comment]
Thank you for you response. It actually worked. But the data I use has no replicates and the output I have is estimation summary. The results look like this: 

Acbd6	NM_001145781.1	1	3.220250353394937e-08	information	1

Can anyone please give me insight if these values are mean ? I have read the documentation. What do the 1 and 2 values mean ? and is 3.220250353394937e-08 the test p-value ?
