### ISSUE TITLE
DAS Error.

### ISSUE THREAD

**Issue by benpiticaru** [WGLab/LIQA#18]
Hi, I am trying to run: 

liqa -task diff <list_of_condition_1> <list_of_condition_2> -out <out_file>

The program runs but only gives the outputs:
DAS testing: Gene AP3S2 being processed...Error in a$v %*% (tx/a$d) : non-conformable arguments
DAS testing: Gene NAA38 being processed...Error in while (testhalf & stepFactor < 11) { :
  missing value where TRUE/FALSE needed
Error in optim(start, fn.opt, method = method, control = control) :
  initial value in 'vmmin' is not finite

I followed to steps laid out in the Usage section to quantify isoform expression and the layout of the condition files is the same as the demo.

Any help would be greatly appreciated.

**Comment by tlz4320** [comment]
I have same problem too, it seems that some isoform have too low expression values. But I don't figure it out.

**Comment by agouru55** [comment]
Hi, apologies for not addressing this issue earlier. Is there a chance you could send the data you have been using so I can take a look at it?
