### ISSUE TITLE
Detecting Alternative Splicing events Error. 

### ISSUE THREAD

**Issue by allapadma** [WGLab/LIQA#19]
Hello, 

I have done the analysis using LIQA. Unfortunately, the data I used doesn't have replicates. The two conditions I provided contain a list of just two individual files. And the output for detecting differential splicing gene/isoform between conditions just gives me the isoform estimation summary and no DAS results. Can you please provide me some insight on what the headers are for these ? 

<img width="668" alt="Screen Shot 2022-03-31 at 11 26 44 PM" src="https://user-images.githubusercontent.com/99461093/161189541-6fad6055-14c5-424b-b139-2ca6c606f28e.png">

**Comment by parsboy66** [comment]
Hi, Actually I have the same problem, 
so far to me it's like: 
gene name, transcript name, splicing id or exon number, p-value


this is what i understand so far, if you have a better idea please share it here, 

I really appreciate the author helping us understand the output of the splicing part.


Thanks

**Comment by huyustats** [comment]
Yes, this is correct. The test unit here is isoform. Thanks
