### ISSUE TITLE
Novel isoforms

### ISSUE THREAD

**Issue by mei-du** [WGLab/LIQA#2]
Hi team, just wanted to confirm or clarify that LIQA only does isoform quantification? If not, is there a way to tell which isoforms are novel? Thanks!

**Comment by huyustats** [comment]
> 
> 
> Hi team, just wanted to confirm or clarify that LIQA only does isoform quantification? If not, is there a way to tell which isoforms are novel? Thanks!

Hi,

Thank you for your interests in LIQA. LIQA is focused on isoform expression quantification and difference detection by accounting for sequencing bias. Currently, LIQA cannot detect novel isoforms.
