### ISSUE TITLE
Problem in finding GCMR packages

### ISSUE THREAD

**Issue by Shafimahmud1** [WGLab/LIQA#20]
Hi I have tried to run following codes , liqa -task diff -condition_1 list1 -condition_2 list2 -out das_detection_results
 but it shows that following error. 
"Error in library("gcmr") : there is no package called ‘gcmr’
Execution halted" 
I have tried to find the following gcmr packages but could not find that.

If you have the package kindly share

**Comment by huyustats** [comment]
Hi @shafijcsmr,

Thanks for your interests in using LIQA. It seems that gcmr was just removed from CRAN. Please have the archive for old version here: https://cran.r-project.org/src/contrib/Archive/gcmr/

**Comment by Vermarashi** [comment]
hi @shafijcsmr,
I already installed gcmr package. Still, I got the same error. 

sudo liqa -task diff -condition_1 estimation/control_isoform_exp
ression_estimates -condition_2 estimation/treatment_isoform_expression_estimates -out ./control_treatment_result
[sudo] password for rverma:
Error in library("gcmr") : there is no package called ‘gcmr’
Execution halted

Could you please tell me what is wrong. should I run this command in R? If not, why it shows this error.

Thanks in advance.

**Comment by agouru55** [comment]
Yes, try running install.packages and library() directly within the R terminal, and see if you run into any issues again.
