### ISSUE TITLE
Estimation of read length survival function

### ISSUE THREAD

**Issue by rob-p** [WGLab/LIQA#21]
Hi,

  Thanks for LIQA!  My student @zzare-umd and I really enjoyed reading the paper and learning about the benefits of modeling the truncated fragment lengths when quantifying isoform abundance from long reads.

  While the paper provides a nice explanation of _what_ is being computed in the estimation equations, we couldn’t find a description of precisely _how_ the Kaplan-Meier estimator is constructed.  We tried to find this in the code, but at least from an initial scan, we weren’t able to isolate that code.  Would you please be able to point us to where in the code we should be looking to see how the Kaplan-Meier estimator is fit, and then applied in the expectation step of the EM algorithm?  Any pointers would be greatly appreciated!

Thanks,
Rob

**Comment by agouru55** [comment]
The estimator is fit and applied in the quantify.py portion of the code. It's not explicitly shown in the script, but in the log file, you can see the KM fitting happening. This is done via the KaplanMeierFitter python command
