### ISSUE TITLE
Output issue

### ISSUE THREAD

**Issue by guandailu** [WGLab/LIQA#22]
Hi,

I want to use liqa in our data, but I found the output is different from what you introduce in the documentation. In our case, there are only two column for the command: liqa -task diff, see below:

GRCg6a_ONTann.16680     0.385391577400457
GRCg6a_ONTann.37369     0.0607042153904338
GRCg6a_ONTann.38298     8.88178419700125e-16
ACOT9   0.240802978269245
GRCg6a_ONTann.30301     0.100841880072923
GRCg6a_ONTann.49536     0.0933312862190236
GRCg6a_ONTann.44592     1
GRCg6a_ONTann.20453     0.523089801356221
GRCg6a_ONTann.7896      1
GRCg6a_ONTann.3738      6.20917433691304e-07
PDCD6   0.0104536083461094
SMARCE1 0.0131009097220072
GRCg6a_ONTann.52006     1
GRCg6a_ONTann.14428     1
GRCg6a_ONTann.28092     1
SEPT2L  1
LSP1P1  1
GRCg6a_ONTann.37210     1
GRCg6a_ONTann.42753     0.157734692020486
ADD3    0
GRCg6a_ONTann.36566     1
GRCg6a_ONTann.30571     1
GRCg6a_ONTann.43828     0.0351664115635129
GRCg6a_ONTann.49474     1
GRCg6a_ONTann.54005     1
HINTW   0.0664120222037035
GRCg6a_ONTann.2160      0.000199730442373647
GRCg6a_ONTann.26090     1
GRCg6a_ONTann.37855     1

How can I explain the two columns?

<img width="511" alt="image" src="https://user-images.githubusercontent.com/33689045/178087605-ce3803ba-7aaa-48bc-b34c-6b3fa6a802cc.png">

**Comment by huyustats** [comment]
Hi, 

Thanks for your interests in using LIQA. The second column is P-Value. I will dig out why Hellinger Distance not in the output file. At this point, you can use P-value to check the expression difference. Thanks.

**Comment by sonyuna90** [comment]
I also have the same issue with the example data you provided. Is there any way to get the Hellinger Distance? Or, just may need to run your R script in the source file?

**Comment by huyustats** [comment]
Hi,

The calculation of Hellinger distance is integrated  in the R program.
Thanks!
