### ISSUE TITLE
fastq file to bam file

### ISSUE THREAD

**Issue by zhanglab2008** [WGLab/LIQA#24]
My Nanopore data are fastq files but the input files need to be in bam format. Do you have a way to convert the fastq files to bam files? Or I can just use Samtools to do that.
Thanks!

**Comment by kaichop** [comment]
FASTQ files are just raw sequence reads. You need to use a mapping software
(for example, minimap2) to map to a reference genome to generate the BAM
file.

**Comment by zhanglab2008** [comment]
Got it thanks!

**Comment by zhanglab2008** [comment]
I still can't get the bam file with the correct format when I used minimap2 and then samtools to sort and index the bam file. The problem is that the "chromosome" column is missing in the sam/bam file from minimap2. I tried to use both transcript and genome gif file to prepare the refgene file but there is no difference. Do you have a tutorial to guide me how to produce the bam file from the ONT full length cDNA reads? Thanks!

**Comment by huyustats** [comment]
Please download genome fasta file instead of gtf file when using minimap2. Here is the tutorial of minimap2: https://lh3.github.io/minimap2/minimap2.html. If you have more question about minimap2, please create an issue at https://github.com/lh3/minimap2. Thanks!

**Comment by zhanglab2008** [comment]
Thanks for the reply. I was able to get the output after I use the full genome fasta file as reference.
