### ISSUE TITLE
what is ReadPerGene_corrected?

### ISSUE THREAD

**Issue by zhanglab2008** [WGLab/LIQA#25]
Hi team,
I wanted to compare the result from LIQA with the result from other tools. I have difficulty in understanding the ReadPerGene_corrected in the output file. What exactly is ReadPerGene_corrected and how to convert this value to TPM or raw count? I can't find any information re: how the ReadPerGene_corrected was calculated.
Much appreciated!

**Comment by huyustats** [comment]
Hi,

Correction here means bias correction in methods part. We treat this corrected count as read count in TPM calculation. Thanks!
