### ISSUE TITLE
reproduce figure 6 in your manuscript

### ISSUE THREAD

**Issue by HaojiaWu** [WGLab/LIQA#27]
Hi team,
Excellent work. I want to reproduce the figure 6 in your manuscript: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02399-8#Sec11
Would you provide more detail how to generate the figure 6? 
More specifically:
1. How did you run LIQA on short-read Illumina data?
2. How did you get the stats for Figure 6A?
3. What software/tool you would recommend to generate Figure 6B?
I want to generate the same graph using my own short-read and long-read data.
Many thanks in advance!

**Comment by huyustats** [comment]
Hi,

Thanks for your interesting in using LIQA.

I used PennSeq and Penndiff to analyze short reads. The stats of DE or non-DE were calculated based on p-values at 0.05 significance level. I used IGV plot to generate the Figure. Thanks!

**Comment by HaojiaWu** [comment]
Thanks that's very helpful! 
I find that the quantify step for long read data (Nanopore) is very slow. I have a bam file with 11GB in size and it ran about 24 hours without completion. Do you have any suggestions for how to improve the run time? Here is the command line I used.
```sh
liqa -task quantify -refgene GRCh38.refgene -bam bp1_sort.bam -out bp1_isoform_expression_estimates -max_distance 10 -f_weight 1
```
I like your tool a lot. Thanks for developing!

**Comment by huyustats** [comment]
Hi,
One reason might be the EM algorithm or KM estimator for each isoform. We are under updating this step (debugging gene-missing problem etc.) and thanks for your feedback. Thanks!

**Comment by HaojiaWu** [comment]
Thanks! look forward to the update.
I am thinking if I should split the bam file into 50 chunks (my server has 56 cores) and run ```quantify``` on each chunk in parallel to speed up the analysis. Then I will merge the results from each chunk after done. Do you think it will affect the outcome?

**Comment by huyustats** [comment]
It should not affect the outcome. Thank you!
