### ISSUE TITLE
High abundance but no reads

### ISSUE THREAD

**Issue by mei-du** [WGLab/LIQA#3]
Hi team,
I've run the isoform quantification pipeline and have discovered this issue. Would you be able to help me clarify it? I've attached some screenshots. IGV inputs are the same as the LIQA ones and I used the recommended parameters. Thank you.
[SAMD11 LIQA example.docx](https://github.com/WGLab/LIQA/files/6032601/SAMD11.LIQA.example.docx)

**Comment by huyustats** [comment]
> Hi team,
> I've run the isoform quantification pipeline and have discovered this issue. Would you be able to help me clarify it? I've attached some screenshots. IGV inputs are the same as the LIQA ones and I used the recommended parameters. Thank you.
> [SAMD11 LIQA example.docx](https://github.com/WGLab/LIQA/files/6032601/SAMD11.LIQA.example.docx)

Hi, would you mind share the sub dataset for this gene and the reference file you used with me to dig out this issue? Thanks!

**Comment by mei-du** [comment]
Just shared my repository with you, thanks!

**Comment by mei-du** [comment]
Hi, could you offer any updates to this issue? Thank you!

**Comment by zjzace** [comment]
Hi,

I also got this issue. Some genes/transcripts with high read coverage but no output from LIQA.

**Comment by huyustats** [comment]
> Hi,
> 
> I also got this issue. Some genes/transcripts with high read coverage but no output from LIQA.

Thanks for your interests in using LIQA. To my experience, reads mapped to unknown isoforms of the gene may cause this issue. We will figure it out soon.

**Comment by agouru55** [comment]
Try running the updated package of LIQA. There is now also a novel isoform detection tool (which you can find on Usage page), which may clarify your issue.
