### ISSUE TITLE
Liqa, DAS: Error in optim(start, fn.opt, method = method, control = control) :   non-finite value supplied by optim

### ISSUE THREAD

**Issue by sigusn** [WGLab/LIQA#32]
Hi

I´m running the demo data you supply. with this command line 
liqa -task diff -condition_1 list1 -condition_2 list2 -out das_detection_results
I get the following output
DAS testing: Gene ATP5PF being processed...Error in optim(start, fn.opt, method = method, control = control) :
  initial value in 'vmmin' is not finite
DAS testing: Gene IL10RB being processed...Error in optim(start, fn.opt, method = method, control = control) :
  non-finite value supplied by optim
DAS testing: Gene S100B being processed...Done!
DAS testing: Gene OLIG1 being processed...Done!
DAS testing: Gene SOD1 being processed...Done!
DAS testing: Gene IFNAR1 being processed...Done!
DAS testing: Gene DSCAM-AS1 being processed...Done!
DAS testing: Gene GABPA being processed...Done!

When opening the das_detection_results file the two genes with error are missing.  Same thing happens when I´m running our own data.
What does this "error in optim" mean and what can be done to resolve it?

**Comment by huyustats** [comment]
Hi,

Basically to generate more reliable detection results, optim function removes genes with expressions that failed in fitting the beta regression model. Let me check the quantification output. Thanks

**Comment by sigusn** [comment]
Thanks, this is just from the demo data I downloaded. So in the isoform_expression_summary all the genes have some values, but the ATP5PF and IL10RB  are missing from the das detection due to this error.
