### ISSUE TITLE
Novel isoform detection

### ISSUE THREAD

**Issue by AlinaO90** [WGLab/LIQA#34]
Hello, the most recent download of this tool includes a function that is not written about here in the documentation:

`liqa -task novel -ref <reference_file> -bamlist <list of bam file> -out <output_file>`

What is the format for the -bamlist needed to run this function? I have tried the following

 -bamlist mapped-BioSample1_filtered.bam [using the bam files filtered with samtools]

which results in error : "BAM file are invalid!"

and 

-bamlist  [mapped-BioSample1_filtered.bam, mapped-BioSample2_filtered.bam, mapped-BioSample3_filtered.bam]

which results in error : " does not exist!"

Thanks!

**Comment by kaichop** [comment]
@huyustats is this problem resolved?

**Comment by huyustats** [comment]
Hi @AlinaO90,

Please update LIQA to the newest version and follow the command of liqa -task novel. The input is bam file. Thanks!
