### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by sonyuna90** [WGLab/LIQA#36]
Hi I have this issue and I have allocated my hpc memory to 150gb currently. Is there any better way to do this process?

Thanks!

# liqa -task diff

DAS testing: Gene MIR99AHG being processed...Error : cannot allocate vector of size 135.7 Gb
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=10538082.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by agouru55** [comment]
Hi - maybe either (1) distributing memory across threads https://github.com/WGLab/LIQA/pull/28  if possible or (2) try filtering out low-confidence reads before quantifying and analyzing.
