### ISSUE TITLE
Issue with DAS estimation and output

### ISSUE THREAD

**Issue by JesusMHU** [WGLab/LIQA#38]
Hi! I'm using liqa -task diff and I got this error: 

Error in optim(start, fn.opt, method = method, control = control) :
  non-finite finite-difference value [4]
DAS testing: Gene AT1G04950 being processed...Done!
DAS testing: Gene AT2G47690 being processed...Done!
DAS testing: Gene AT4G10710 being processed...Done!
DAS testing: Gene AT1G08660 being processed...Error in chol.default(K) :
  la submatriz de orden 7 no es definida positiva
Error in chol.default(K) :
  la submatriz de orden 7 no es definida positiva
Error in optim(start, fn.opt, method = method, control = control) :
  valor inicial en 'vmmin' no es finito
DAS testing: Gene AT2G44710 being processed...Error in optim(start, fn.opt, method = method, control = control) :
  valor inicial en 'vmmin' no es finito
DAS testing: Gene AT2G29200 being processed...Error in optim(start, fn.opt, method = method, control = control) :
  non-finite finite-difference value [6]
Error in optim(start, fn.opt, method = method, control = control) :
  non-finite finite-difference value [4]
DAS testing: Gene AT4G02640 being processed...Error in optim(start, fn.opt, method = method, control = control) :
  valor inicial en 'vmmin' no es finito
Error in optim(start, fn.opt, method = method, control = control) :
  valor inicial en 'vmmin' no es finito

Dont know what could be causing it. Then when it finished I checked the output and it looked like this only: 

AT5G51040	1
AT5G21160	0.963366399306107
AT1G07940	0.999999985914178
AT3G27470	0.650819005674937
AT2G37620	0.0892513703148758
AT3G25520	0.209992684655096
AT3G13460	0.00173611833872689
AT1G19835	0.168765918241626
AT4G39270	0.00393607527406237
AT1G15200	0.804948525950204
AT1G09570	0.109291374080427
AT1G15750	0.320812516518486
AT1G66410	0.521182338746133
AT5G62090	0.0270380833171076
AT4G35080	0.0978038264531164
AT5G55390	0.774214007413218
AT1G08570	1
AT2G40540	0.0575474227202776
AT5G03240	1
AT2G18960	0
AT4G10590	0.0536774503331144
AT5G13980	1
AT5G43310	0.576011640598243
AT2G39770	1
AT5G19140	0.984938255511173
AT5G66310	0.900582119308603
AT3G43190	1
AT1G18660	0.137197682158356
AT2G41060	0.091576656013638

**Comment by JesusMHU** [comment]
Hi! Any update on this? I could really really use the help here!

**Comment by agouru55** [comment]
Hi, sorry for the delay! From the error messages, it looks like there was a problem with the optimization of the EM algorithm. I would try updating to the latest version of LIQA to debug and also double check the parameters you're using for the diff step along with correct formatting of the input data (esp because you were able to process some of the genes)
