### ISSUE TITLE
about gcmr

### ISSUE THREAD

**Issue by border-info-nt** [WGLab/LIQA#44]
Hello,

I'm using LIQA for my research and encountering an error with gcmr during the final stage, Step 3: Detecting differential splicing gene/isoform between conditions. I've tried installing it in R, but without success. Could you please advise on how to resolve this issue?

Thank you.

**Comment by kaichop** [comment]
did you check the several solutions at https://github.com/WGLab/LIQA/blob/master/doc/Install.md

**Comment by border-info-nt** [comment]
I followed the steps as indicated by the URLs, but I'm still encountering problems. When I try to install the package using R CMD INSTALL gcmr_1.0.2.tar.gz, I receive the following warning and error:

Warning: invalid package ‘gcmr_1.0.2.tar.gz’
Error: cannot open file ‘gcmr_1.0.2.tar.gz’: No such file or directory

Why is this happening?

**Comment by agouru55** [comment]
Hi, I looked into this issue and it might be because there's an updated version of gcmr of 1.0.3.  You can try again with the command above or could download directly from this link: https://cran.rstudio.com/src/contrib/gcmr_1.0.3.tar.gz. Thanks!

**Comment by border-info-nt** [comment]
Hi

I am currently using a MacBook Pro with an M2 chip. Could that be related to the issue?
I am also using Python 3.11.6 and R 4.3.3. It is possible that these versions are not supported.
I have tried the following link as well: https://cran.rstudio.com/src/contrib/gcmr_1.0.3.tar.gz, but it didn't work.
Would it be possible for you to provide specific code examples?
If it's beyond my skill level, I would appreciate it if you could suggest alternative methods similar to LIQA.

Thank you!!

**Comment by kaichop** [comment]
The executables are typically compiled for x86 processors.
If you must use M2, then you have to download and install docker (load a
Linux image) and then run all software tools within docker. I do not know
how/whether other software can be run on M2.

**Comment by border-info-nt** [comment]
Hello,

I was able to install gcmr using R terminal, but now I'm facing another issue.

DAS testing: Gene CTD-2643I7.5 being processed...Error in optim(start, fn.opt, method = method, control = control) :
initial value in 'vmmin' is not finite
DAS testing: Gene ARRDC1-AS1 being processed...Error in optim(start, fn.opt, method = method, control = control) :
initial value in 'vmmin' is not finite
Error in if (grepl("Error", fit.H0) == T) { :
the condition has length > 1
Execution halted

Do you know how to resolve this issue?
Thank you!

**Comment by agouru55** [comment]
Hello, please feel free to check within some of the closed issues such as #32 and a few others, as other users have run into this error. The optim function basically removes genes with expressions that failed in fitting the beta regression model. I don't seem to run into an error when running on the example data or any other sets. I'd first check the other closed issues and if your problem isn't resolved, be sure to check the format of your input file (esp because some genes likely were able to get processed) and if not I can take a look. Thanks!
