### ISSUE TITLE
Error while runing Liqa quantification

### ISSUE THREAD

**Issue by EglantineMB** [WGLab/LIQA#45]
thank you very much for developping this tool that seem super promising!

I am trying to run the quantification step, but always run into the following error which I result in quantification of some but not all isoforms.

PB.10903        processing...
PB.10903        7 iterations    Done!
PB.129  processing...
PB.129  11 iterations   Done!
Traceback (most recent call last):
  File "/XXX/site-packages/liqa_src/quantify.py", line 202, in <module>
    exonStarts[i-1] = int(tmpinf[3])+1
                      ^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

Note that when I regenerate the refgen file, them the script stop at a different isoform. 

thank you in advance for your help!

**Comment by agouru55** [comment]
Hi, thanks so much for the message and apologies for the delay in response! I believe issue #4 is closest to your concerns but I would check over your refgen file again. The error message looks to be affiliated with an error associated with that isoform in your refgene file. Perhaps take a look at that again to make sure it is being used optimally to generate the EM matrix and quantify
