### ISSUE TITLE
assign reads to transcript

### ISSUE THREAD

**Issue by enovoa** [WGLab/LIQA#7]
Hello! Thanks for making this software available. I was wondering if there is some way to obtain the assignments of readIDs to transcripts that are done by LIQA? Thanks in advance! Eva

**Comment by huyustats** [comment]
Hi @enovoa ,

Thanks for your interests in using LIQA. Read isoform compatibility matrix is a intermediate information of LIQA. Some reads are assigned to multiple isoforms due to 3' bias. Therefore, LIQA does not output this information directly. Thanks!

**Comment by bernicegu313** [comment]
Hi@huyustats
Hello! Thanks for making this software available。 I have a question，Is the quantitative result of the corrected full-length transcript? Could this software be used to quantify the new transcripts?

**Comment by huyustats** [comment]
Hi @bernicegu313, thanks for your interests in LIQA. Yes, the corrected estimation is the result. LIQA can quantify new transcripts when these transcripts are annotated in refgene file. Thanks!
